[[redirects]]
  from = "/"
  to = "https://my.condexpress.com/:splat"
  status = 302
  force = true
  [redirects.query]
    condominio = ":condominio"

[[redirects]]
  from = "/*"
  to = "https://my.condexpress.com/:splat"
  status = 302
  force = true